- name: Template .vimrc
  template:
    src: '.vimrc.j2'
    dest: '{{ ansible_user_dir }}/.vimrc'
    mode: '0644'

- name: Create dein directory
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ dein.install_dir }}'
    - '{{ dein.rc_dir }}'

- name: Copy dein installer.sh
  copy:
    src: 'dein/{{ dein.install_script }}'
    dest: '{{ dein.install_dir }}'
    mode: '0644'

- name: Install dein
  command: 'sh {{ dein.install_script }} dein'
  args:
    creates: '{{ dein.install_dir }}/dein'
    chdir: '{{ dein.install_dir }}'
  when: not ansible_check_mode

- name: Copy toml files
  copy:
    src: 'dein/{{ item }}'
    dest: '{{ dein.rc_dir }}/{{ item }}'
    mode: '0644'
  loop:
    - '{{ dein.toml }}'
    - '{{ dein.lazy_toml }}'
  when: not ansible_check_mode
