- name: Remove installed docker
  dnf:
    name: '{{ item }}'
    state: absent
  become: yes
  loop:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  when: (docker_version.failed) or
        (docker_version.stdout is version_compare(docker.version, '<'))

- name: Install packages
  dnf:
    name: '{{ item }}'
    state: present
  become: yes
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docker yum repositry
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install newest docker
  yum:
    name: '{{ item }}'
  become: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    group: docker
    append: yes
  become: yes

- name: Ensure docker service is enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: yes
  when: (docker_compose_version.failed) or
        (docker_compose_version.stdout is version_compare(docker_compose.version, '<'))