- name: check docker version
  command: docker version -f \{\{.Server.Version\}\}
  changed_when: false
  ignore_errors: yes
  register: docker_version

- name: check docker compose version
  command: docker-compose version --short
  changed_when: false
  ignore_errors: yes
  register: docker_compose_version

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  become: yes

- name: Include Redhat Docker task
  include: docker_redhat.yml
  tags: [ redhat ]
  when: ansible_os_family == "RedHat"

- name: Include Debian Docker task except Ubuntu20.04
  include: docker_debian.yml
  tags: [ debian ]
  when: ansible_os_family == "Debian"
