- name: copy config file
  copy:
    src: 'fish/config.fish'
    dest: '{{ ansible_user_dir }}/.config/fish/'
    mode: '0644'

- name: register fish path
  command: 'which fish'
  register: fish_path
  changed_when: False
  check_mode: no

- name: apply fish to user shell
  user:
    name: '{{ ansible_user_id }}'
    shell: '{{ fish_path.stdout }}'
  when: ansible_user_shell != fish_path.stdout
  become: yes

# - name: Download oh-my-fish
#   get_url:
#     url: https://get.oh-my.fish
#     dest: /tmp/get.oh-my.fish
#     mode: '0755'

# - name: Execute oh-my-fish
#   command: 'fish /tmp/get.oh-my.fish'
#   args:
#     creates: '~/.config/fish/conf.d/omf.fish'

# - name: Remove oh-my-fish
#   file:
#     path: /tmp/get.oh-my.fish
#     state: absent
