---
# tasks file for roles
- name: Include packages task
  include: packages.yml
  tags: [ packages ]

- name: Include docker task
  include: docker.yml
  when: ansible_os_family in ("RedHat","Debian")
  tags: [ docker, packages ]

- name: Include rbenv task
  include: rbenv.yml
  when: ansible_os_family in ("RedHat","Debian")
  tags: rbenv

- name: Include git task
  include: git.yml
  tags: git

- name: Include dein task
  include: dein.yml
  tags: dein

- name: Include fish task
  include: fish.yml
  tags: fish

- name: Include dotfiles task
  include: dotfiles.yml
  tags: dotfiles
