- name: Install fish for Centos8
  get_url:
    url: 'https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo'
    dest: /etc/yum.repos.d/
  become: yes
  when:
    - ansible_distribution_major_version | float == 8

- name: Install dnf for Centos7
  block:
    - name: Change interpreter
      set_fact:
        ansible_python_interpreter: "/usr/bin/python"

    - name: Install epel-release
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Install dnf
      yum:
        name: dnf
        state: present
      become: yes
  when:
    - ansible_distribution_major_version | float < 8

- name: Install epel-release
  dnf:
    name: epel-release
    state: present
  become: yes

- name: Install common packages
  become: yes
  dnf:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop: '{{ packages }}'