- name: Add apt repository
  apt_repository:
    repo: "ppa:fish-shell/release-3"
  become: yes
  when: ansible_distribution_version | float < 20.04

- name: Install common packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  become: yes
  loop: '{{ packages }}'