---
# tasks file for roles/homebrew
- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Homebrew tap
  homebrew_tap:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ brew_taps }}'

- name: Install Homebrew Cask Packages
  homebrew:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_cask_apps }}'
  failed_when: false

- name: Install Homebrew Packages
  homebrew:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_packages }}'