---
dependency:
  name: galaxy
driver:
  # name: delegated
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-centos7}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
